// This file is auto-generated by the Supabase CLI
// Run: npm run types:generate:local
// 
// Generated types will appear below this comment

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          owner: string
          title: string
          description: string | null
          status: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          owner: string
          title: string
          description?: string | null
          status?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          owner?: string
          title?: string
          description?: string | null
          status?: string
          created_at?: string
          updated_at?: string
        }
      }
      notes: {
        Row: {
          id: string
          project_id: string
          title: string | null
          content: string
          order_index: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          project_id: string
          title?: string | null
          content: string
          order_index?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          title?: string | null
          content?: string
          order_index?: number
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_user_projects: {
        Args: {
          user_id: string
        }
        Returns: {
          id: string
          title: string
          description: string | null
          status: string
          created_at: string
          updated_at: string
          notes_count: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}

// Helper types for better developer experience
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type Inserts<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type Updates<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']

// Specific table types
export type Profile = Tables<'profiles'>
export type Project = Tables<'projects'>
export type Note = Tables<'notes'>

export type ProfileInsert = Inserts<'profiles'>
export type ProjectInsert = Inserts<'projects'>
export type NoteInsert = Inserts<'notes'>

export type ProfileUpdate = Updates<'profiles'>
export type ProjectUpdate = Updates<'projects'>
export type NoteUpdate = Updates<'notes'>

// Function return types
export type UserProjectWithCount = Database['public']['Functions']['get_user_projects']['Returns'][0]
